Support for git repo as an upstream source
aristanetworks/eos-external-tools pull request #114
Opened 2024-06-25 13:57 UTC by manith-arista

In addition to tarball and srpms, eext now supports git repo as an upstream source.

2024-06-25 14:00 UTC, manith-arista commented
Pending tasks:
1. Change implementation of `git clone`
2. Add support for `local-eextsubdir`
3. Find method to verify git repo with eext keychain, change signature check default to False for now.
4. Change `Source0` in spec file to use generic

2024-06-27 09:28 UTC, aajith-arista requested changes

2024-06-27 09:28 UTC, aajith-arista commented on manifest/manifest.go
> +	Version string `yaml:"rel-version"`
What's Version ?

2024-06-27 09:28 UTC, aajith-arista commented on manifest/manifest.go
> +	Snapshot     GitSnapshot  `yaml:"snapshot"`
Does it make sense if we don't re-use full-url ?
Maybe have something like
```
gitSpec GitSpec `yaml:"git"`
```
type GitSpec struct {
    url string `yaml:"url"`
    commit string `yaml:"commit"`
    atCommitOrTag string `yaml:"at"`
}
```
What's Version ?
Do we need to separate commit or tag(lightweight/annotated) in the yaml ? Isn't that something we can figure out ourself after snapshotting ?

2024-07-02 11:59 UTC, manith-arista commented on manifest/manifest.go
> +	Version string `yaml:"rel-version"`
As discussed, we will use the commit/tag revision as a unique identifier for creating tarball, instead of a user defined version.

2024-07-02 11:59 UTC, manith-arista commented on manifest/manifest.go
> +	Snapshot     GitSnapshot  `yaml:"snapshot"`
Updated with suggested format

2024-08-13 15:14 UTC, manith-arista commented
eext now supports `git` as an upstream source. Users can now add the url to the upstream git repo, along with the revision(commit/tag) at which they want to snapshot.
This PR is the first part of the 'git as upstream source' commit.

We intend to add another variant `git-worktree`, which will let us embed an `eext.yaml` to an existing internal git repo, to convert it into an eext package.

2024-08-14 07:07 UTC, aajith-arista requested changes
pls also add live code review comments notes here

2024-08-22 07:11 UTC, manith-arista commented
Comments from the live code review

- Don't use upstream repo as test case, instead fork the repo to a local repo (which will be the way forward for git as a source repos). Check with `openssh` team to get more details on how to go about this.
- For now, create a git repo within `testData` and use it as a source.
- Define naming convention for the forked repo (should be same as upstream)
- Split `create_srpm` into separate implementation for `git` and other sources.

2024-09-20 04:10 UTC, aajith-arista submitted a review, later dismissed

2024-09-28 12:12 UTC, manith-arista commented on impl/create_srpm_from_git_test.go
> +	suppressCmdArgs := []string{"chown", "-R", strings.TrimSpace(user), clonedDir}
Added a check to suppress Git Error 128 (dubious ownership).
```
upstream_git_test.go:206: invalid revision libpcap-1.10.1 provided, provide either a COMMIT or TAG git show of repo /tmp/upstream-git-test3396308859/libpcap failed exit status 128
fatal: detected dubious ownership in repository at '/tmp/upstream-git-test409732300/libpcap'
To add an exception for this directory, call:

        git config --global --add safe.directory /tmp/upstream-git-test409732300/libpcap
```

This arises due to the git repo being created by me, hence when Barney runs the test, it does not have the right file permissions to execute git commands

2024-09-28 12:12 UTC, manith-arista commented
Rebased PR to the latest commit

2024-10-04 09:00 UTC, aajith-arista approved these changes

2024-10-04 09:44 UTC, merged