SHA-256 hash support for unverified upstream sources
aristanetworks/eos-external-tools pull request #147
Opened 2024-12-13 05:46 UTC by manishk-arista

Unverified upstream sources (those with `skip-check: true`) are inherently risky as they lack a verification method. Any changes to these sources could go undetected. To address this, we now calculate and store the SHA-256 hash of unverified sources. This hash is added to the `eext.yaml` file under the `src-sha256-hash` field. During the `create-srpm` command, the hash in `eext.yaml` will be compared with the hash of the downloaded sources.

2024-12-16 07:31 UTC, manith-arista requested changes

2024-12-16 07:31 UTC, manith-arista commented on impl/create_srpm.go
> +func generateSrcSha256Hash(srcFilePath string) (string, error) {
Lets keep this function independent of the file type, so that we can reuse it later

2024-12-16 07:31 UTC, manith-arista commented on impl/create_srpm.go
> +		if upstreamSrcFromManifest.Signature.SkipCheck && upstreamSrcFromManifest.Signature.SrcSha256Hash != "" {
Fail if `skipcheck` is true but no sha256 is provided

2024-12-16 07:31 UTC, manith-arista commented on impl/create_srpm.go
> +			srcFilePath := filepath.Join(downloadDir, upstreamSrc.sourceFile)
Skip this check for `git` sources, since a hash doesn't make sense for a repo

2024-12-16 07:31 UTC, manith-arista commented on manifest/manifest.go
> +	SrcSha256Hash     string            `yaml:"src-sha256-hash"`
`src` is implied since it is within source field.
Name can be workshopped, @arun-arista to provide inputs.

My suggestion: `file-hash: <hash>`

2024-12-16 08:32 UTC, manishk-arista commented on impl/create_srpm.go
> +		if upstreamSrcFromManifest.Signature.SkipCheck && upstreamSrcFromManifest.Signature.SrcSha256Hash != "" {
This change it for time being while we make changes into `eext.yaml` of repos. It will remove it.

2024-12-18 07:53 UTC, aajith-arista commented on impl/create_srpm.go
> +func generateSha256Hash(filePath string) (string, error) {
Move to util package

2024-12-18 07:53 UTC, aajith-arista commented on impl/create_srpm.go
> +		if upstreamSrcType != "git-upstream" && upstreamSrcFromManifest.Signature.SkipCheck && upstreamSrcFromManifest.Signature.SrcSha256Hash != "" {
This code can go inside getUpstreamSourceForOthers 

Inside you can use conditional of `if sha256`
Let's not enforcer sha256 presence for skip-check:true now.
We can do enforcement in a later PR

2024-12-18 07:53 UTC, aajith-arista commented on impl/create_srpm.go
> +			eextSha256Hash := upstreamSrcFromManifest.Signature.SrcSha256Hash
Just call this `sha256InManifest` ?

2024-12-18 07:53 UTC, aajith-arista commented on impl/create_srpm.go
> +			}
Can you please wrap the strings ?

2024-12-18 07:53 UTC, aajith-arista commented on manifest/manifest.go
> +	SrcSha256Hash     string            `yaml:"src-sha256-hash"`
Can we move this to `UpstreamSrc`.
Also just call this `sha256`

2024-12-20 07:43 UTC, aajith-arista commented on impl/create_srpm_for_others.go
> +			return nil, fmt.Errorf("SHA256 hash '%s'is not matching with "+
"Bad SHA256: 'foo' expected: 'bar'"

2024-12-20 07:43 UTC, aajith-arista commented on manifest/manifest.go
> +	SHA256       string       `yaml:"sha256"`
SHA256 -> Sha256

2024-12-20 07:43 UTC, aajith-arista commented on util/util.go
> +		return "", fmt.Errorf("errored with %s while generating hash",
fnt.Errorf( "%sGenerateSha256Hash: errored out with '%s', 
                   errPrefix, err )

2024-12-20 07:43 UTC, aajith-arista commented on impl/create_srpm_for_others.go
> +		sha256Hash, err := util.GenerateSha256Hash(srcFilePath)
Pass errPrefix too

2024-12-20 07:43 UTC, aajith-arista commented on impl/create_srpm_for_others.go
> +			return nil, fmt.Errorf("SHA256 hash '%s'is not matching with "+
Pass  errPrefix down

2024-12-20 07:43 UTC, aajith-arista commented on impl/create_srpm_from_others_test.go
> +func TestUpstreamSourcesSHA256Hash(t *testing.T) {
Also add a test case where sha256 check fails.

2024-12-20 07:43 UTC, aajith-arista commented on util/util.go
> +		return "", fmt.Errorf("errored with %s while creating file",
fnt.Errorf( "%sGenerateSha256Hash: errored out with '%s', 
                   errPrefix, err )

2024-12-20 07:43 UTC, aajith-arista commented on impl/testData/upstream-src-hash/eext.yaml
> +---
Rename dir as `upstream-hash-check-good`
Also add a bad eext.yaml case under `upstream-hash-check-bad`

2024-12-20 07:43 UTC, aajith-arista commented on impl/create_srpm_from_others_test.go
> +	t.Log("TestupstreamSourcesSHA256Hash test passed")
remove

2024-12-23 06:58 UTC, manishk-arista commented on impl/testData/upstream-src-hash/eext.yaml
> +---
present test case is checking for bas SHA256 hash

2024-12-27 07:10 UTC, manith-arista commented on manifest/manifest.go
> +	Sha256       string       `yaml:"Sha256"`
Shall we go with `sha256` in the yaml file? All other fields follow lowercase convention.

2024-12-27 07:10 UTC, manith-arista commented on impl/create_srpm_for_others.go
> +	if upstreamSrcFromManifest.Sha256 != "" {
This logic can be moved to a separate function. This will help you write test cases specifically for success/fail of signature check, instead of running create-srpm command

2025-01-09 09:56 UTC, manith-arista submitted a review, later dismissed

2025-01-10 09:17 UTC, manith-arista commented on impl/create_srpm_from_others.go
> +	srcFilePath := filepath.Join(downloadDir, sourceFile)
We can pass `srcFilePath` as an input to the function, instead of having 2 input parameters to determine this

2025-01-10 09:18 UTC, manith-arista commented on impl/create_srpm_from_others.go
> +		return fmt.Errorf("%s SHA256 generation failed with '%s'", errPrefix, err)
`srcFilePath` will also help in debugging the error log

2025-01-10 09:19 UTC, manith-arista commented on impl/create_srpm_from_others.go
> +		return fmt.Errorf("%s bad SHA256: '%s' expected: '%s'",
Add `srcFilePath` to the error log here as well.

2025-01-10 09:21 UTC, manith-arista commented on impl/create_srpm_from_others_test.go
> +	CheckSHA256HashErr := checkSHA256Hash(downloadDir, sourceFile,
Variables starting with capitals are considered global. Use camelCase format for local variables.

2025-01-10 09:23 UTC, manith-arista commented on impl/create_srpm_from_others_test.go
> +	require.NotEqual(t, nil, err)
You may use `require.Error()` to assert a non-nil error

2025-01-10 09:23 UTC, manith-arista commented on impl/create_srpm_from_others_test.go
> +	require.Equal(t, nil, err)
You may use `require.NoError()` to assert nil error

2025-01-10 10:47 UTC, manith-arista approved these changes

2025-01-13 05:56 UTC, merged