add root command to list unverified upstream sources
aristanetworks/eos-external-tools pull request #148
Opened 2024-12-13 08:04 UTC by manishk-arista

This new root command is part of the `stest` and is designed to list all upstream sources with the `skip-check` flag set to `true`.
- If `-p <package>` is specified, it lists unverified sources for the specified package.
- Otherwise, it lists all unverified upstream sources in the repository.

The output is written to:
`/dest/code.arista.io/eos/eext/{rep}/{package}.unverifiedSources.json`.

This file will be included in the Barney snapshot build, enabling better tracking of unverified sources.

2024-12-16 08:58 UTC, manith-arista requested changes

2024-12-16 08:58 UTC, manith-arista commented on impl/list_unverified_sources.go
> +		upstreamInfoFile := fmt.Sprintf("/dest/code.arista.io/eos/eext/%s/%s/unVerifiedSources.json", repoName, thisPkgName)
Create a constant string for the file path

2024-12-18 06:02 UTC, manith-arista requested changes

2024-12-18 06:02 UTC, manith-arista commented on impl/list_unverified_sources_test.go
> +	ListUnverifiedSources(repo, "foo1")
Use a for loop for test cases, as it is easier to add new tests.
```
testCases := map[string]string {
    "foo1": "/dest/code.arista.io...",
    "foo2": "..."
}

for pkg, filePath in range(testCases) {
    ListUnverifiedSources(repo, pkg)
    require.Equal(t, nil, checkFileExists(filePath))
}
```

2024-12-18 06:02 UTC, manith-arista commented on cmd/list_unverified_sources.go
> +	Long: `Checks for the upstream sources within package which don't have a valid signature check i.e, skip-check flag is true
Although Golang doesn't have a prescribed line width, try to wrap long lines for easier reading

2024-12-18 10:14 UTC, mkisielewski-arista requested changes
Some questions, suggestions posted below.
Overall the function introduced here does some logic and writes a file in the end. Which makes the testing of it difficult. If the logic would be separate from writing the tests could be easier to write, stateless, and would not need to be run in a container.

2024-12-18 10:14 UTC, mkisielewski-arista commented on impl/list_unverified_sources.go
> +			return nil
This return also breaks the loop, meaning subsequent packages will not get checked. Do we want this? Maybe we should have some comment justifying dropping the rest of the check if that's really wanted.

2024-12-18 10:14 UTC, mkisielewski-arista commented on impl/list_unverified_sources.go
> +}
There's already a function like that in the util module.

2024-12-18 10:14 UTC, mkisielewski-arista commented on impl/list_unverified_sources.go
> +	var checkAllPackages bool = (pkg == "")
```suggestion
	checkAllPackages := pkg == "" // if pkg name has not been specified, check all
```

2024-12-18 10:14 UTC, mkisielewski-arista commented on impl/list_unverified_sources_test.go
> +			require.Equal(t, nil, checkFileExists(filePath))
Either we stick with the standard assertions if we only need simple assertions. Or, if we decide to use a more complicated 3rd party lib for assertions, let's use what it has, namely `NoError` here. This way the extra function would not be needed.

2024-12-18 10:14 UTC, mkisielewski-arista commented on impl/list_unverified_sources_test.go
> +		filePath := fmt.Sprintf("/dest/code.arista.io/eos/eext/impl/%s/unVerifiedSources.json", pkg)
The file is not deleted afterwards.

2024-12-18 10:14 UTC, mkisielewski-arista commented on impl/list_unverified_sources_test.go
> +func TestListUnverifiedSources(t *testing.T) {
Should we check for the contents of the files as well?

2024-12-19 05:32 UTC, manishk-arista commented
> Some questions, suggestions posted below. Overall the function introduced here does some logic and writes a file in the end. Which makes the testing of it difficult. If the logic would be separate from writing the tests could be easier to write, stateless, and would not need to be run in a container.

I have made some previously discussed changes to code. Now I have removed some part of code and made changes to existing ones. I think most of the review comments are addressed in these new changes.

2024-12-20 09:14 UTC, aajith-arista commented on impl/list_unverified_sources.go
> +		return fmt.Errorf("listUnverifiedSources - '%s' package is not part of this repo", pkg)
can you make the error message in the same format as other subcommands

2024-12-20 09:14 UTC, aajith-arista commented on impl/list_unverified_sources.go
> +			return fmt.Errorf("listUnverifiedSources - errored with %s", err)
`fmt.Errorf( "impl.ListUnVerifiedSources: Error '%s' unmarshaling yaml" )`
to be consistent with rest of the code

2024-12-20 09:14 UTC, aajith-arista commented on impl/list_unverified_sources.go
> +func fetchUpstreamSrcsWithSkipCheck(upstreamSrcManifest []manifest.UpstreamSrc) []manifest.UpstreamSrc {
Can you rename this as `getUpstreamSrcsWithSkipCheck` to not confuse with `fetchUpstream` which actually downloads the sources.

2024-12-20 09:14 UTC, aajith-arista commented on impl/list_unverified_sources_test.go
> +//go:build containerized
this doesn't have to be containerized.

2024-12-23 06:37 UTC, aajith-arista submitted a review, later dismissed

2024-12-30 07:02 UTC, manith-arista commented on impl/list_unverified_sources_test.go
> +		"foo2": `- source-bundle:
Does golang not have a way to indent these multi line string?

2024-12-30 12:50 UTC, mkisielewski-arista commented on impl/list_unverified_sources_test.go
> +		"foo2": `- source-bundle:
I'd love to see python's textwrap.dedent() too 🥲 

Looking at this from readability point of view, we have a key + a multiline string content. Sounds a lot like a file, so maybe it'd be easier to just encode the in.yaml + out.yaml (or .txt if it's not fully valid yaml). It's not like it's gonna make the tests much more complex (they already require quite the brainpower for the piping to click :) )

2024-12-30 13:39 UTC, manishk-arista commented on cmd/list_unverified_sources.go
> +	Args: cobra.ExactArgs(0),
This check is to fail the case if someone class `eext list-unverified-sources -p libtool bandit`, we can remove this check if needed. I just added it to avoid invalid invocations.

2024-12-30 13:43 UTC, manishk-arista commented on impl/list_unverified_sources.go
> +	if !pkgFound {
this check is to error out if this command is invoked for the package which is not present in eext.yaml. 
`len(upstreamSources)` can also be 0 for the packages which don't have `skip-check` flag for upstream sources.

2025-01-09 09:46 UTC, manith-arista commented on cmd/list_unverified_sources.go
> +	Args: cobra.ExactArgs(0),
This makes sense, lets have the check intact

2025-01-10 09:14 UTC, manith-arista commented on impl/list_unverified_sources_test.go
> +		t.Errorf("impl.TestListUnverifiedSources: errored failed while reading %s file", filePath)
Use `t.Fatal` instead to kill the test, `Error` will continue execution

2025-01-10 09:14 UTC, manith-arista commented on impl/list_unverified_sources_test.go
> +	require.NotEqual(t, nil, err)
You can use `require.Error(t, err)` to specify that the function should return an error

2025-01-10 12:01 UTC, manith-arista approved these changes

2025-01-16 08:52 UTC, manith-arista submitted a review, later dismissed
Ensure rebase is done before merging

2025-01-16 10:34 UTC, mkisielewski-arista approved these changes
Looks awesome, +1.

BTW
I noticed that some of the new files have 2022 and others 2023 in the topmost comment. Of course it's not a problem, but I think it'd be better to have this an actual year of the file creation, or make it consistent with the project.

2025-01-17 10:29 UTC, manith-arista approved these changes

2025-01-17 15:45 UTC, merged