eext: Adding source bundle capability for eext packages to invoke using repoName
aristanetworks/eos-external-tools pull request #88
Opened 2023-09-06 08:13 UTC by manith-arista

2023-09-06 08:50 UTC, aajith-arista commented on manifest/manifest.go
> +	FullURL         string                         `yaml:"full-url"`
This should be outside the `SourceBundle` type.
Maybe retain `UpstreamSrc` type?
```
type UpstreamSrc struct {
     Bundle SourceBundle `yaml:"source-bundle"`
     FullURL string `yaml:"full-url"`
}
```

2023-09-06 08:55 UTC, aajith-arista commented on manifest/manifest.go
> +	"code.arista.io/eos/tools/eext/srcconfig"
note for future (no need to change this)

Since you are refering to srcconfig here, it might have been better to put srcconfig changes also in this commit. or define the interface in a common ancestor commit.

2023-09-06 08:57 UTC, aajith-arista commented on cmd/testData/debugedit-1/eext.yaml
> +          full-url: https://artifactory.infra.corp.arista.io/artifactory/eext-sources/eext-testData/debugedit-5.0-3.el9.src.rpm
You could use `{{.Host}}`

2023-09-06 08:57 UTC, aajith-arista commented on cmd/testData/debugedit-2/eext.yaml
> +          full-url: https://artifactory.infra.corp.arista.io/artifactory/eext-sources/eext-testData/debugedit-5.0-3.el9.src.rpm
same comment here

2023-09-06 09:05 UTC, aajith-arista commented on manifest/manifest.go
> +	Signature       srcconfig.UpstreamSrcSignature `yaml:"signature"`
Signature can also move out. Also better to define the type in manifest package itself.

Signature can now be something like
type DetachedSignature struct {
    Suffix string `yaml:"suffix"`
    FullUrl string `yaml:"full-url"`
    OnUncompressed `yaml:"suffix"`
}
type Signature struct {
    SkipCheck bool  `yaml:"skip-check"`
    DetachedSignature  DetachedSignature `yaml:"detached-sig"`
}

2023-09-06 09:12 UTC, aajith-arista commented on impl/create_srpm.go
> +				return fmt.Errorf("%sBundle %s not found in manifest", bldr.errPrefix,
Say Source bundle specifically in error messages so as not to confuse users with repo bundle

2023-09-06 09:15 UTC, aajith-arista commented on srcconfig/srcconfig.go
> +	SrcFormat         string               `yaml:"source-fmt"`
You can just say type is `Format` and yaml annotaion is `format`.
Src part is obvious from nesting

2023-09-06 09:18 UTC, aajith-arista commented on srcconfig/srcconfig.go
> +	Signature UpstreamSrcSignature
Can we call this SrcURL and SignatureURL instead ?
And name the container type `SrcParams` to be consistent with `DnfRepoParams`

2023-09-06 09:18 UTC, aajith-arista commented on srcconfig/srcconfig.go
> +func (s *SrcBundle) GetSrcBundle(
We'll all it `GetSrcParams`

2023-09-06 09:21 UTC, aajith-arista commented on configfiles/srcconfig.yaml
> +    source-fmt: "{{.Host}}/artifactory/eext-sources/tarballs/{{.PkgName}}/{{.Version}}/{{.PkgName}}.tar.gz"
We cannot assume `tar.gz` as suffix ?
We can add a `Suffix` to manifest and if it is empty and also add a `DefaultSuffix` here in the bundle.

2023-09-06 09:25 UTC, aajith-arista commented on cmd/testData/debugedit-2/eext.yaml
> +          full-url: https://artifactory.infra.corp.arista.io/artifactory/eext-sources/eext-testData/debugedit-5.0-3.el9.src.rpm
And maybe you could change one of this to actually exercise the bundle code.

And do add separate unit tests to just check the bundle code.

2023-09-06 09:30 UTC, aajith-arista reviewed
Hi Manith,
Thanks for doing this cleanly.
I've some suggestions on how the type hierarchies should be. 
General approach is good.

Thanks,
Arun

2023-09-11 11:11 UTC, aajith-arista commented on srcconfig/srcconfig.go
> +	subVer = "v" + subVer
Why do we need this.
Let the entire string be the version/version-override

2023-09-11 11:13 UTC, aajith-arista commented on srcconfig/srcconfig_test.go
> +		"pkg", "srpm", "bundle-srpm", "default", "", "", false, "", "", false)
Please have this in a loop testing all three cases
1. version = ""
2. version = "someLabel"
3. version = "notLabel"

2023-09-11 11:15 UTC, aajith-arista commented on srcconfig/srcconfig_test.go
> +	t.Log("Signature Check")
Trace it as `Signature Path Check`. 
Signature check is confusing as we don't check signatures here

2023-09-11 11:16 UTC, aajith-arista commented on srcconfig/srcconfig_test.go
> +		"pkg", "srpm", "bundle-srpm", "default", "", "", false, "", "", false)
Also can we use a different host than https://artifactory.corp... set with `SrcRepoHost`. Let's check the  viper config too

2023-09-11 11:17 UTC, aajith-arista commented on srcconfig/srcconfig_test.go
> +		"http://foo.org/artifactory/custom_signature.asc", "", false)
Better to have a loop of test cases.

2023-09-11 11:18 UTC, aajith-arista commented on srcconfig/srcconfig_test.go
> +	require.Error(t, paramsErr3)
What are we covering extra here ?

2023-09-11 11:23 UTC, aajith-arista commented on impl/create_srpm.go
> +		if sourceBundleFromManifest.Name != "" {
I think you can actually check for empty bundle with
```
bundleFromManifest == SrcBundle{}
```

2023-09-11 11:24 UTC, aajith-arista commented on impl/create_srpm.go
> +				return bundleErr
fmt.Errorf and return like other cases in this method

2023-09-11 11:25 UTC, aajith-arista commented on srcconfig/srcconfig.go
> +	Signature UpstreamSrcSignature
I think this should be 
```
   SignatureURL string
```

2023-09-11 11:27 UTC, aajith-arista commented on impl/create_srpm.go
> +
This shouldn't be implemented in create_srpm. This should be abstracted by `GetSrcParams`. Whatever it returns should be the expanded template

2023-09-11 11:29 UTC, aajith-arista commented on srcconfig/srcconfig.go
> +func FormatURLTemplate(srcURLFormat, sigURLFormat string) (string, string, error) {
Make this a single function
Arg can be `urlFormat`. It can be called twice by caller with `srcURLFormat` and `sigURLFormat`.
That's the cleaner approach.

And I said, let the caller be `GetSrcParams` not a function in `impl/create_srpm.go`

2023-09-12 13:36 UTC, manith-arista commented on srcconfig/srcconfig_test.go
> +	require.Error(t, paramsErr3)
This test covers the error scenario when no version is passed for tarball

2023-09-12 13:40 UTC, manith-arista commented on srcconfig/srcconfig_test.go
> +		"pkg", "srpm", "bundle-srpm", "default", "", "", false, "", "", false)
> Also can we use a different host than https://artifactory.corp... set with `SrcRepoHost`. Let's check the viper config too

Are you referring to the Line 15, where we set Viper config of SrcRepoHost to a custom URL?

2023-09-14 06:15 UTC, manith-arista commented on manifest/testData/sampleManifest1.yaml
> +            full-url: http://foo/tcpdump.tar.xz.sig
Added negative test cases in this review

2023-09-14 06:17 UTC, manith-arista commented on srcconfig/srcconfig.go
> +	onUncompressed bool,
Changed the design to use Override

2023-09-14 12:58 UTC, aajith-arista requested changes
Hi Manith
Thanks for making the changes previously requested.
A few more changes, but it's quite close now

2023-09-14 12:58 UTC, aajith-arista commented on manifest/manifest_test.go
> +		require.Error(t, err)
Also check if error has the expected error message. Use an extra `ErrorContains`. expected message substring can be part of Variant

2023-09-14 12:58 UTC, aajith-arista commented on impl/create_srpm.go
> +		srcParamsFromManifest, err := srcconfig.GetSrcParams(
You shouldn't call this `srcParamsFromManifest` because it combines manifest and config, let's just call it `srcParams`.

2023-09-14 12:58 UTC, aajith-arista commented on impl/create_srpm.go
>  		}
We can skip this. I think we should have sufficient assertions in GetSrcParams. If it returns success, we should be good.

2023-09-14 12:58 UTC, aajith-arista commented on impl/create_srpm.go
> +		signatureURL := srcParamsFromManifest.SignatureURL
Remove and use the rhs directly ?

2023-09-14 12:58 UTC, aajith-arista commented on srcconfig/srcconfig.go
> +		return "", fmt.Errorf("srcconfig.formatURLTemplate: Error parsing source URL %s", urlFormat)
Use bldr.ErrPrefix

2023-09-14 12:58 UTC, aajith-arista commented on srcconfig/srcconfig.go
> +	fullURL, err := formatURLTemplate(fullURL)
I see the reason for this wrapper now.
But let's call this `GetSrcParamsWithNoBundle`.
And call either this or the method from `create_srpm`

2023-09-14 13:12 UTC, aajith-arista commented on srcconfig/srcconfig.go
> +		Host string
Can we add a PathPrefix too.
We'll also add a vipe config `SrcRepoPathPrefix` defaulting to `artifactory/eext-sources/...`

2023-09-19 06:30 UTC, aajith-arista approved these changes
Thanks for taking care of all the comments patiently.
Nicely done!

2023-10-03 09:24 UTC, aajith-arista reviewed
LGTM
Will approve once all the 3rd party muts are also ready

2023-11-02 10:49 UTC, aajith-arista approved these changes
Thanks for getting this done

2023-11-02 15:52 UTC, merged